name: build

on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache install Nix packages
      uses: rikhuijzer/cache-install@v1.0.8
      with:
        key: nix-${{ hashFiles('shell.nix') }}
        nix_file: 'shell.nix'
    - name: Build and test
      run: nix-shell --run 'make ci'

